### ISSUE TITLE
ContentProvider.createUri 

### ISSUE THREAD

**Issue by argjendhaxhiu** [twotoasters/SectionCursorAdapter#26]
In the MainActivity.java in the sample folder you have called the function in this way:
@Override
    public Loader<Cursor> onCreateLoader(int id, Bundle args) {
        String orderBy = ToasterModel.SHORT_JOB + " ASC, " + ToasterModel.NAME + " ASC";
        return new CursorLoader(this, ContentProvider.createUri(ToasterModel.class, null), null, null, null, orderBy);
    }

and this cannot be compiled because there is no method named createUri() on ContentProvider, whether static or otherwise !!!

**Comment by MinceMan** [comment]
That uses ActiveAndroid's ContentProvider. I would not have named it the
same as the system one but I did not write that library. The jar is in the
libs folder, not sure why Android Studio isn't picking it up for you.
