### ISSUE TITLE
onItemClick detects badly if you clicked on the section or on the item

### ISSUE THREAD

**Issue by tolmachevroman** [twotoasters/SectionCursorAdapter#27]
Hi,

 there's a bug that I was facing in the first version and now in the second one too: in the onItemClick listener it often confuses _section_ and an _item_. So sometimes it returns Object when you click on the section, sometimes Cursor, and the same with the items.

**Comment by frakc** [comment]
@tolmachevroman 
you can either find what you clicked yourself (example below) or set separate listeners for section and item and use them instead of onItemclickedlistener

``` java
    list.setOnItemClickListener(new AdapterView.OnItemClickListener() {

      @Override public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
        Cursor c = mAdapter.getCursor();
        int newPosition = mAdapter.getCursorPositionWithoutSections(position - 1);
        if (newPosition != -99) {
          c.moveToPosition(newPosition);
          // you clicked section, do whatever you need
        }else{
              Object section = getSections()[getIndexWithinSections(position)];

         //you clicked section
      }
    });
```

**Comment by MinceMan** [comment]
RecycerView doesn't have onItemClickListeners so this won't be a thing with 3.0. I'm going to close this.
