### ISSUE TITLE
NoClassDefFoundError in MultiDex mode

### ISSUE THREAD

**Issue by a7madev** [twotoasters/SectionCursorAdapter#28]
When Multidex is enabled, this error is shown 
java.lang.NoClassDefFoundError: com.example.adapter.viewholders.SectionViewHolder
is there any way to fix this issue?

Im using 
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

```
defaultConfig {
    multiDexEnabled true
}
dependencies {
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.twotoasters.SectionCursorAdapter:library:2.0.1'
    compile 'com.android.support:support-v4:23.1.1'
}
```

**Comment by MinceMan** [comment]
It seems to be fine in 3.0 but I have this feeling that that is a proguard issue. I'm going to close this. Once 3.0 is out if you still have the problem reopen an issue. I'm guessing you are not using this lib because of that :-P

**Comment by a7madev** [comment]
Yes it is a proguard issue but how can we solve it? what parameters should I use in proguard for your library? I prefer this lib because the setup is easy but I removed it because of the issue :-D
